site_name: Toby's bookmark

nav:
  - Home: index.md
  - 书签导航: bookmark.md
  - Bookmark - HTML Format: bookmark.html

theme:
  name: material
  custom_dir: overrides
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: 切换到深色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: 切换到浅色模式
  logo: images/favicon.ico
  favicon: images/favicon.ico
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.suggest
    - search.highlight

extra_css:
  - stylesheets/bookmark.css

copyright: "Copyright &copy; 2020 - 2026 Toby Liu. All Rights Reserved."

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true

repo_url: https://github.com/liuning0820/bookmark
repo_name: GitHub
edit_uri: tree/master/docs/

extra:
  generator: false
  social:
    - icon: material/home
      link: ./
      name: Home
    - icon: material/linkedin
      link: http://www.linkedin.com/in/toby-liu-86750923/
      name: LinkedIn
  analytics:
    provider: google
    property: G-44TYLJ4BRN

plugins:
  - search
  - git-revision-date
